name: API Automation Tests

on:
  push: 
    branches:
      - Main
      - emile
  pull_request:
    branches:
      - Main

jobs: 
  api-tests: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 10.0.302

      - name: Restore dependencies
        run: dotnet restore

      - name: Create appsettings.json
        run: |
          cat > appsettings.json << EOF
          {
            "Application": {
              "BaseUrl": "https://restful-booker.herokuapp.com"
            },
            "Authentication": {
              "Username": "${{ secrets.API_USERNAME }}",
              "Password": "${{ secrets.API_PASSWORD }}"
            }
          }
          EOF

      - name: Build project
        run: dotnet build --no-restore

      - name: Run API tests
        run: dotnet test --no-build --verbosity normal