name: API Automation Tests

on:
  push: 
    branches:
      - Main
      - emile
  pull_request:
    branches:
      - Main

  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Select the test suite to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - smoke
          - auth
          - booking   

jobs: 
  api-tests: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 10.0.302

      - name: Restore dependencies
        run: dotnet restore

      - name: Create appsettings.json
        run: |
          cat > appsettings.json << EOF
          {
            "Application": {
              "BaseUrl": "https://restful-booker.herokuapp.com"
            },
            "Authentication": {
              "Username": "${{ secrets.API_USERNAME }}",
              "Password": "${{ secrets.API_PASSWORD }}"
            }
          }
          EOF

      - name: Build project
        run: dotnet build --no-restore

      - name: Run API tests
        shell: pwsh
        run: |
          switch ("${{ inputs.test_suite }}") {
            "smoke" {
              .\Scripts\run-smoke.ps1
            }
            "auth" {
              .\Scripts\run-auth.ps1
            }
            "booking" {
              .\Scripts\run-booking.ps1
            }
            default {
              .\Scripts\run-all.ps1
            }
          }      